import Foundation

enum RepositoryHealthRecipes {
    static let recipes: [RepairRecipe] = [
        RepairRecipe(id: "git.unpublishedBranches", title: "Review unpublished branch work", prompt: "Inspect the identified branch and compare its commits with fresh remote refs, including patch-equivalent work where useful. Explain what work remains unpublished and how to preserve it. Ask before pushing, deleting branches, moving refs or changing history. Preserve all working trees and staged changes. Do not switch branches automatically."),
        RepairRecipe(id: "git.upstream", title: "Review upstream tracking", prompt: "Inspect the reported branch configuration and refresh remote refs. Determine whether it is intentionally local, its remote branch was deleted, or it should track an existing branch. Ask before selecting or changing its upstream or publishing it. Preserve branch history and local changes; do not switch branches or push automatically."),
        RepairRecipe(id: "files.secrets", title: "Review potential exposed credentials", prompt: "Inspect the reported secret location without printing credentials, token fragments or surrounding sensitive source. Determine whether it is an intentional fixture. For real credentials, explain rotation and revocation and ask for any required user action; removing a file does not revoke exposure. Replace hardcoded credentials with the project's intended configuration and preserve useful examples. Do not rewrite history, push, revoke credentials or call external services without explicit authorization. Leave changes uncommitted."),
        RepairRecipe(id: "dependencies.lockfileDrift", title: "Synchronize manifest and lockfile", prompt: "Inspect manifest and lockfile changes, workspace ownership, the intended package manager and repository dependency policy. Determine which declaration is intended and update the matching lockfile using that manager while preserving supply-chain protections and avoiding unrelated upgrades. Verify synchronization with the manager's supported checks. Preserve unrelated staged changes. Leave changes uncommitted; do not publish."),
        RepairRecipe(id: "dependencies.runtime", title: "Align runtime versions", prompt: "Inspect runtime constraints and version files, CI matrices and container versions. Preserve intentionally supported test matrices. Reconcile incompatible versions using the project's supported runtime; ask if choosing a new runtime would alter compatibility. Verify appropriate builds or tests without unnecessary dependency upgrades. Leave changes uncommitted; do not publish."),
        RepairRecipe(id: "ci.security", title: "Review workflow security", prompt: "Inspect the specific workflow risks. Pass untrusted event text through quoted environment variables, scope token writes to the jobs that require them, and prevent privileged workflows from executing untrusted pull-request code. Preserve legitimate release permissions and behavior. Validate the workflow and relevant local checks. Leave changes uncommitted; do not trigger remote workflows or change repository-level settings."),
        RepairRecipe(id: "files.oversized", title: "Review large tracked assets", prompt: "Inspect the reported file and determine whether it is an intentional source asset, generated output, dataset or checkpoint. Explain appropriate storage or a reasoned threshold exception. Ask before removing tracked assets, migrating files to LFS, downloading content or rewriting history. Preserve local files and unrelated staged work. Leave changes uncommitted."),
        RepairRecipe(id: "git.checkoutIntegrity", title: "Review submodule and LFS checkout", prompt: "Inspect the reported submodule or LFS path, its intended commit or content, and local changes. Determine whether the checkout is deliberately partial or the submodule update intentional. Ask before network downloads or changing submodule commits and preserve local work. Do not blindly update recursively, execute hooks or reset files. Do not commit, push or change branches."),
        RepairRecipe(id: "files.mergeMarkers", title: "Resolve leftover conflict markers", prompt: "Inspect the complete conflict blocks and repository context. Preserve deliberate examples and fixtures with reasoned exceptions. Resolve accidental leftovers by understanding both sides, without dropping unrelated work or weakening tests. Run relevant validation. Leave changes uncommitted; do not abort Git operations or change branches."),
        RepairRecipe(id: "files.projectReferences", title: "Repair project references", prompt: "Inspect the missing workspace member, action, script or package entry point. Distinguish generated build output from missing source. Correct stale references or restore intended files using repository evidence; preserve workspace exclusions and legitimate build paths. Verify affected tooling with appropriate local checks. Leave changes uncommitted; do not run arbitrary referenced scripts just to inspect them or publish.")
    ]
}
